### ISSUE TITLE
demo will not run

### ISSUE THREAD

**Issue by hanssl** [Scandit/barcodescanner-sdk-for-web-samples#17]
Steps to reproduce:
1. git clone https://github.com/Scandit/barcodescanner-sdk-for-web-samples.git
2. nom install nap
3. cd barcodescanner-sdk-for-web-samples/react-samples/react
4. npm start
5. observe the error:

<img width="1172" alt="Screen Shot 2020-12-19 at 4 13 05 AM" src="https://user-images.githubusercontent.com/649957/102687987-c92ab180-41b0-11eb-9d4b-7e2e6266c0b7.png">

**Comment by Shyiy** [comment]
As the error states, the global `nwb` package version you have installed is too recent and doesn't correspond to the older version required by the package.json in this project (which hasn't been updated in a while).
I updated this and other demos' dependencies to make things work, please pull the latest changes.

**Comment by hanssl** [comment]
It appears that the problem is related to NextJs.  I pulled your latest code and was able to launch the demo.

However, whenever I try to import Scandit-sdk into a nextjs project it complains about 'navigator' not being defined.  Attached is a vanilla nextjs project created by:

1. 'npx create-next-app'
2. name it 'test'
3. cd test
4. add 'import { configure, BarcodePicker as ScanditSDKBarcodePicker } from "scandit-sdk";' to the top of index.js
5. 'npm add Scandit-sdk'
6. 'npm install'
7. 'npm run dev'
8. Observe that the application will not load.


![Screen Shot 2020-12-21 at 3 44 38 PM](https://user-images.githubusercontent.com/649957/102829068-7cf39300-43a3-11eb-81ba-777facdb71da.png)
[test.zip](https://github.com/Scandit/barcodescanner-sdk-for-web-samples/files/5726868/test.zip)

**Comment by Shyiy** [comment]
The problem is that you are loading our library in a server rendering context provided by Next.js which doesn't provide all the client browser APIs and variables needed.
See for example: https://github.com/vercel/next.js/discussions/11027
or many other similar related problems on the same repository.
You need to load and use the library on the client side as explained by Next.js documentation and support.

**Comment by hanssl** [comment]
I changed the page to load your script client side (see below).  The console reports errors and the camera is not triggered.

`import Head from 'next/head'
import { useEffect } from 'react'

export default function Barcode(props) {

    useEffect(() => {

        ScanditSDK.configure("AeqPOVzyQ416FGqLkC6b80omKuPUM/SsJhXqKftZuLXvNnxndgW0ydJOYnwwTLiC2mZQMCcFtFz1dK1niDr8DABHh8/+fAIMd1KV33RtNR6MbM6qCnJMdXI3AoU+IN48iCXo3bcQc9654uaJZ4aLaPkRnED+60c3vWxtYbL1ccDuuyiCalcoB8WGVoItMKpDshiESqcN0SnOA/LXQ57KF0rHMLYMHgbcAVOAbDjm/7IVAYeUZRnsig9539NadFDbylhb4oT/8KcIfdaUitrn6fO748Wt05fsjq5aLBqP8Xp0X1sAxL8cg15gRy9gqzibLqe3Mh48+v3LtPBM+O3MiV5nGprj+ocjJUa7zt90QcWwQuX3UUGEeLHFNE3nFiW887NRyECDX2ZgaVBP0oncVlbSZhoZmn+vb7HX6iwvywxYEVekWrMdx9i0V4ULfbocKMsjrpFGcxgq9qk+uMokW1Ezz59tt1US33R35EO9rGbbspbglUWYkgyiGo1vr1hs1c4pZVF26Fmgjn/G5f4gFmPpPhgLgXr4+9balu6y/w/KPJk599W9MJto+a70HicZ2ktcedtFx2RDTEiiL/MMLYUEfDKLmlEg3QvwQLjbcqJgE2IPCR5Cdfsyr32jgj3Foi1HcXrH7D/Rpc0CJL9jLOtXisTEbzFA9X18wfLy2FnGUogVeTdcKs0jtzxnZIgD+Jw8E65QH/srXyo3IEJTYU4qozO9907V5m2ZC7Rioc+55sIH/fNdYAXzNLONp7hf6ZE4EHjJkxnzp3XPAtfpmMmMVwv5eVMKwesv9MOC1jgZ6qW3LU8=", {
            engineLocation: "https://cdn.jsdelivr.net/npm/scandit-sdk@5.x/build/",
        })
            .then(() => {
                return ScanditSDK.BarcodePicker.create(document.getElementById("scandit-barcode-picker"), {
                    // enable some common symbologies
                    scanSettings: new ScanditSDK.ScanSettings({ enabledSymbologies: ["ean8", "ean13", "upca", "upce"] }),
                });
            })
            .then((barcodePicker) => {
                // barcodePicker is ready here, show a message every time a barcode is scanned
                barcodePicker.on("scan", (scanResult) => {
                    alert(scanResult.barcodes[0].data);
                });
            });
    }, [])

    return (
        <>
            <Head>
                <title>Barcode scanner</title>
                <script src="https://cdn.jsdelivr.net/npm/scandit-sdk@5.x"></script>
            </Head>

            <div>
                Barcode scanner 2
            </div>

            <div id="scandit-barcode-picker"></div>
        </>
    )
}
`

<img width="1242" alt="Screen Shot 2020-12-22 at 10 50 06 AM" src="https://user-images.githubusercontent.com/649957/102918208-bc71bc00-4443-11eb-8b95-ad206d160e37.png">

**Comment by hanssl** [comment]
I tried to follow the url in the console output (https://cdn.jsdelivr.net/npm/index.min.js.map) and the browser reports a 404.

![Uploading Screen Shot 2020-12-22 at 10.56.11 AM.png…]()

**Comment by ScanditSupport** [comment]
Hi @hanssl 
would you mind reaching out to us directly with your individual issue?
https://support.scandit.com/hc/en-us/requests/new

It would allow us to support you in getting the setup running. 
Best regards
Scandit Support
