### ISSUE TITLE
The camera cannot scan in real time in the area, only click to take a picture

### ISSUE THREAD

**Issue by MuseVickie** [Scandit/barcodescanner-sdk-for-web-samples#19]
The configuration is as follows：
const CONFIG = {
    sdk: {
        apiKey: licensKey2,
        engineLocation: 'https://cdn.jsdelivr.net/npm/scandit-sdk@5.x/build',
    },
    barcodePicker: {
        playSoundOnScan: true,
        vibrateOnScan: true,
        accessCamera: false,
        visible: false,
        guiStyle: 'none',
        videoFit: ScanditSDK.BarcodePicker.ObjectFit.COVER,
        cameraSettings: {
            resolutionPreference: ScanditSDK.CameraSettings.ResolutionPreference.FULL_HD
        }
    },
    scanSettings: {
        enabledSymbologies: DEFAULT_SYMBOLOGIES,
        codeDuplicateFilter: -1,
        maxNumberOfCodesPerFrame: 3,
    },
    activeSymbolCountMin: 5,
    activeSymbolCountMax: 35,
}

async function scanConfig() {
    await ScanditSDK.configure(CONFIG.sdk.apiKey, {engineLocation: CONFIG.sdk.engineLocation})
        .then(() => ScanditSDK.BarcodePicker.create(appElement.barcodePickerContainer, CONFIG.barcodePicker)
            .then((createdPicker) => {
                const scanSettings = new ScanditSDK.ScanSettings(CONFIG.scanSettings);
                appElement.barcodePicker = createdPicker;
                appElement.barcodePicker.applyScanSettings(scanSettings);

                appElement.barcodePicker
                    .on('scan', onScan)
                    .on('scanError', onScanError)
                    .on('ready', onPickerReady);
            })
        )
        .catch((err) => {
            console.log('------error', err);
            alert('sdk configure default');
        })
}

const onStart = () => {
    appElement.barcodeSpanDom.innerHTML = '';
    results = [];
    appElement.barcodePicker
        .accessCamera()
        .then(onCameraAccess)
        .catch(onCameraError);
}

const onScan = scanResult => {
    console.log('scanResult', scanResult);
    
    scanResult.barcodes.forEach(barcode => {
        if (results.includes(barcode.data)) return;

        results.push(barcode.data);
        appElement.barcodeSpanDom.innerHTML = results.join(';')

        if (results.length >= 1) {
            appElement.scanStopBtn.classList.remove('disabled');
        }
    });
}

**Comment by Shyiy** [comment]
Unless you provide more information, we can only speculate that the "single image mode" being used is correctly caused and triggered as a fallback by your application/website running on a browser/OS with no video streaming capabilities.

**Comment by MuseVickie** [comment]
1.What information also needs to be provided？
2.The example of turning on the official website on the same device can be scanned normally
3.You are using a registration test licensKey

**Comment by ScanditSupport** [comment]
@MuseVickie we are happy to support you with your individual request via our support team. Please reach out to us and provide OS & browser version as well as above code snippet via our webform support.scandit.com 

Best regards
Scandit Support
