### ISSUE TITLE
Could not explicitly change colorInvertedEnabled

### ISSUE THREAD

**Issue by mohitkmr170** [Scandit/barcodescanner-sdk-for-web-samples#4]
Not able to manipulate colorInvertedEnabled value of dot code Symbology to true, it takes the default set value, i.e 'false'

**Comment by Shyiy** [comment]
Did you call applyScanSettings (https://docs.scandit.com/stable/web/classes/barcodepicker.html#applyscansettings) with the new settings? Modifying the ScanSettings object only doesn't apply it yet to the BarcodePicker/Scanner.
Can you share a code snippet if it still doesn't work?

**Comment by mohitkmr170** [comment]
Hey, It worked in a different way, by applying scansettings on that
particular symbology
Thanks
