### ISSUE TITLE
Browser window Crash in iOS

### ISSUE THREAD

**Issue by hkkr123git** [Scandit/barcodescanner-sdk-for-web-samples#5]
We are experiencing a browser window crash while using Scandit web sdk. this issue exists only in Safari. Cant trace out the issue. After two successfull scans there will be a banner displayed top of the browser window by saying "**A Problem occurred with this webpage so it is reloaded.**" It happens couple of times. After some times browser window closes clearing all the localstorage values and cookies. This occurred after ScandIt library integration.

**Comment by AlexWattrelos** [comment]
Hi,

Thanks for reaching out. Could you reach out to support@scandit.com with:
- code snippet
- logs you are seeing in the console
- iOS version

Best,

Alex
