### ISSUE TITLE
NotReadableError: Could not start video source

### ISSUE THREAD

**Issue by getcontrol** [Scandit/barcodescanner-sdk-for-web-samples#6]
Android Chrome

**Comment by Shyiy** [comment]
As explained here:
https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia
That error usually means there's a lower level (OS/hardware) preventing the page/browser from accessing the camera. You might want to try to just restart the device.

**Comment by getcontrol** [comment]
Fixed with suggestion
